---
title: "team.Rmd"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(ggplot2)
choco <- read.csv("https://xdaiisu.github.io/ds202materials/hwlabs/choco.csv")
```

```{r}
#1

str(choco$Rating)
summary(choco$Rating)
sum(table(choco$Rating))


```
# 1852 chocolate bars were rated in this data set.

```{r}
#2
summary(choco$Review.Date)
table(choco$Review.Date) 


barplot(table(choco$Review.Date))

ggplot(choco,  aes(x = Review.Date))+
  geom_bar(colour = "black")+
  ggtitle("Number of Reports") 
  


```


```{r}
#3
#summary(choco$Company.Location)
#sum(table(choco$Company.Location))
sort(table(choco$Company.Location), decreasing = TRUE)


num_Rate_Comp_Locate <- factor(choco$Company.Location, levels = names(sort(table(choco$Company.Location))))




ggplot(choco, aes(x = num_Rate_Comp_Locate))+
  geom_bar()+
  theme(text = element_text(size = 7))+
  coord_flip()+
  ggtitle("Ratings Compared Across Different Company Locations")


```



# Question:  What Company produces the chocolate with the highest coco percentages on average
```{r}
#4 and #5

num <- choco[, c('Company','Cocoa.Pct' )]
num2 <- aggregate(choco$Cocoa.Pct, by = list(Company = choco$Company), data = choco, FUN = mean)
num2
num2[order(-num2$x), ] #I do not take credit for this line of code.  A fellow student on piazza help answer my question! 
```
#Bouga Cacao produces the chocolate with the highest coco percentages on average.